
package com.webservice.controller;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.webservice.customer.generated.wsdl.CustomerSoapType;
import com.webservice.customer.generated.wsdl.CustomerType;
import com.webservice.customer.generated.wsdl.ListOfCustomerType;
import com.webservice.customer.generated.wsdl.ObjectFactory;



/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source
 * version: 2.2
 * 
 */
@WebServlet("/ws/CustomerSoapBndTypePort/test")
@WebService(name = "CustomerSoapType", targetNamespace = "http://test.co.id/ws/customer/")
public class CustomerSoapTypeImpl extends HttpServlet implements CustomerSoapType {

	private static Logger logger = LoggerFactory.getLogger(CustomerSoapTypeImpl.class);

	/**
	 * Request All Customer
	 * 
	 * @param parameters
	 * @return returns id.co.bca.ws.mbs.model.ListOfCustomerType
	 */
	
	@WebMethod(operationName = "GetAllCustomer")
	@WebResult(name = "GetAllCustomerResponse", targetNamespace = "http://test.co.id/ws/customer/", partName = "parameters")
	public ListOfCustomerType getAllCustomer() {
		ObjectFactory objectFactory = new ObjectFactory();
		ListOfCustomerType listOfCustomerType = objectFactory.createListOfCustomerType();
		CustomerType cusType = new CustomerType();
		cusType.setAge(10);
		cusType.setName("wahyu");
		listOfCustomerType.getListOfCustomer().add(cusType);
		return listOfCustomerType;

	}

	/**
	 * Insert Customer
	 * 
	 * @param parameters
	 * @return returns java.lang.String
	 */
	public String insertCustomer(CustomerType parameters) {
		return null;
	}

}
